### ISSUE TITLE
Update to bevy 0.13

### ISSUE THREAD

**Issue by funatsufumiya** [zimond/lottie-rs#15]
I'm now trying to create PR to migrate to bevy 0.13.

https://github.com/funatsufumiya/lottie-rs/commit/633ab4e9446f084eae40bb4c8d30f1a654257713

However, shader validation error occurs while `$ cargo r --release -- --input fixtures/ui/drink.json`. Any helps are welcome...

```
2024-04-10T22:09:16.018344Z ERROR log: Device::create_shader_module error:
Shader validation error:
  ┌─ :1:1
  │
1 │
  │
  │
  │ naga::Expression [6]
  │ invalid function call


2024-04-10T22:09:16.023935Z ERROR bevy_render::render_resource::pipeline_cache: failed to create shader module: Validation Error

Caused by:
    In Device::create_shader_module

Shader validation error:
  ┌─ :1:1
  │
1 │
  │
  │
  │ naga::Expression [6]
  │ invalid function call
```

**Comment by funatsufumiya** [comment]
For this, I also upgraded bevy_tweening capture_fn branch to bevy 0.13.
https://github.com/funatsufumiya/bevy_tweening/commit/eb37435c04f3dd226bd3784664f4f42b8d57bc7e

Confirmed mainly working well, but only one test is not passing:

```
test plugin::tests::change_detect_component ... FAILED

failures:

---- plugin::tests::change_detect_component stdout ----
thread 'plugin::tests::change_detect_component' panicked at src/plugin.rs:175:43:
Requested resource bevy_time::time::Time does not exist in the `World`.
                Did you forget to add it using `app.insert_resource` / `app.init_resource`?
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.


failures:
    plugin::tests::change_detect_component

test result: FAILED. 45 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.38s
```

**Comment by zimond** [comment]
thanks for the report, I'll try to get some time to investigate this

**Comment by funatsufumiya** [comment]
Sorry, I didn't notice this!

> by the way is it OK if I directly upgrade to bevy 0.13

Sure, thank you :)

**Comment by funatsufumiya** [comment]
Confirmed working :)
I have some lottie json files not working properly, but these also not working in [rlottie](https://github.com/Samsung/rlottie).
- [test1.lottie.json](https://github.com/zimond/lottie-rs/files/15240772/test1.lottie.json)
- [test2.lottie.json](https://github.com/zimond/lottie-rs/files/15240775/test2.lottie.json)
- [test3.lottie.json](https://github.com/zimond/lottie-rs/files/15240781/test3.lottie.json)

**Comment by zimond** [comment]
I'll investigate them. Thanks!
