### ISSUE TITLE
Does not compile on current stable rust

### ISSUE THREAD

**Issue by SirVer** [zimond/lottie-rs#6]
Thanks for this neat project, it looks great!

I'd like to experiment with this crate to turn animations from our design department into PNGs, which we can then crush into MJPEG images to put on an old display, that only supports animations in that form. It seems that it is up to the task, as long as it renders the lottie files all correctly. However, this would require this to compile on stable rust, which it currently does not.

It seems `font-toolkit` is using feature gates which are not supported in stable rust. 

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/hrapp/.cargo/git/checkouts/font-toolkit-845b82da456935bf/c3e2bc4/src/lib.rs:1:1
  |
1 | #![feature(doc_auto_cfg)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
```

**Comment by SirVer** [comment]
When fixing this one, the next problem is in this crate itself:

```
   Compiling lottie-player v0.1.0 (/Users/hrapp/src/lottie/lottie-rs/crates/player)
error[E0554]: `#![feature]` may not be used on the beta release channel
 --> crates/player/src/main.rs:1:12
  |
1 | #![feature(path_file_prefix)]
  |            ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `lottie-player` (bin "lottie-player") due to 1 previous error
```

**Comment by zimond** [comment]
Yes indeed I'm getting too comfort to use nightly rust... Will fix this in a few days
